import { CobblerInputChoices, CobblerInputData } from '../utils';

export const cobblerItemReadonlyData: Array<CobblerInputData> = [
  {
    formControlName: 'name',
    inputType: CobblerInputChoices.TEXT,
    label: $localize`:@@item.edit.label.name:Name`,
    disabled: false,
    readonly: true,
    defaultValue: '',
    inherited: false,
    hint: $localize`:@@item.edit.hint.name:The item's name. Used as the primary identifier across the Cobbler API and CLI.`,
  },
  {
    formControlName: 'uid',
    inputType: CobblerInputChoices.TEXT,
    label: $localize`:@@item.edit.label.uid:UID`,
    disabled: false,
    readonly: true,
    defaultValue: '',
    inherited: false,
    hint: $localize`:@@item.edit.hint.uid:The internal unique identifier assigned by Cobbler. Never reused, even after deletion.`,
  },
  {
    formControlName: 'mtime',
    inputType: CobblerInputChoices.TEXT,
    label: $localize`:@@item.edit.label.mtime:Last modified time`,
    disabled: false,
    readonly: true,
    defaultValue: '',
    inherited: false,
    hint: $localize`:@@item.edit.hint.mtime:Timestamp of the last change to this item via the Cobbler API.`,
  },
  {
    formControlName: 'ctime',
    inputType: CobblerInputChoices.TEXT,
    label: $localize`:@@item.edit.label.ctime:Creation time`,
    disabled: false,
    readonly: true,
    defaultValue: '',
    inherited: false,
    hint: $localize`:@@item.edit.hint.ctime:Timestamp of when this item was first created in Cobbler.`,
  },
  {
    formControlName: 'depth',
    inputType: CobblerInputChoices.NUMBER,
    label: $localize`:@@item.edit.label.depth:Depth`,
    disabled: false,
    readonly: true,
    defaultValue: 0,
    inherited: false,
    hint: $localize`:@@item.edit.hint.depth:Logical depth of this item in the hierarchy. Controls load order and sorting.`,
  },
  {
    formControlName: 'is_subobject',
    inputType: CobblerInputChoices.CHECKBOX,
    label: $localize`:@@item.edit.label.is_subobject:Is Subobject?`,
    disabled: false,
    readonly: true,
    defaultValue: false,
    inherited: false,
    hint: $localize`:@@item.edit.hint.is_subobject:Whether this item is a sub-object of another item (e.g. a sub-profile or sub-system).`,
  },
];

export const cobblerItemEditableData: Array<CobblerInputData> = [
  {
    formControlName: 'comment',
    inputType: CobblerInputChoices.TEXT,
    label: $localize`:@@item.edit.label.comment:Comment`,
    disabled: true,
    readonly: false,
    defaultValue: '',
    inherited: false,
    hint: $localize`:@@item.edit.hint.comment:A free-text note or description to associate with this item.`,
  },
];
