import {Injectable} from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ItemSettingsService {
  mockdata = {
    allow_duplicate_hostnames: [0, 'bool'],
    allow_duplicate_ips: [0, 'bool'],
    allow_duplicate_macs: [0, 'bool'],
    allow_dynamic_settings: [0, 'bool'],
    always_write_dhcp_entries: [0, 'bool'],
    anamon_enabled: [0, 'bool'],
    auth_token_expiration: [3600, 'int'],
    authn_pam_service: ['login', 'str'],
    autoinstall_snippets_dir: ['/var/lib/cobbler/snippets', 'str'],
    autoinstall_templates_dir: ['/var/lib/cobbler/templates', 'str'],
    bind_chroot_path: ['', 'str'],
    bind_master: ['127.0.0.1', 'str'],
    boot_loader_conf_template_dir: ['/etc/cobbler/boot_loader_conf', 'str'],
    bootloaders_dir: ['/var/lib/cobbler/loaders', 'str'],
    grubconfig_dir: ['/var/lib/cobbler/grub_config', 'str'],
    build_reporting_enabled: [0, 'bool'],
    build_reporting_ignorelist: ['', 'str'],
    build_reporting_sender: ['', 'str'],
    build_reporting_smtp_server: ['localhost', 'str'],
    build_reporting_subject: ['', 'str'],
    buildisodir: ['/var/cache/cobbler/buildiso', 'str'],
    cache_enabled: [1, 'bool'],
    cheetah_import_whitelist: [['re', 'random', 'time'], 'list'],
    client_use_https: [0, 'bool'],
    client_use_localhost: [0, 'bool'],
    cobbler_master: ['', 'str'],
    convert_server_to_ip: [0, 'bool'],
    createrepo_flags: ['-c cache -s sha', 'str'],
    default_autoinstall: ['/var/lib/cobbler/templates/default.ks', 'str'],
    default_name_servers: [[], 'list'],
    default_name_servers_search: [[], 'list'],
    default_ownership: [['admin'], 'list'],
    default_password_crypted: ['\$1\$mF86/UHC\$WvcIcX2t6crBz2onWxyac.', 'str'],
    default_template_type: ['cheetah', 'str'],
    default_virt_bridge: ['xenbr0', 'str'],
    default_virt_disk_driver: ['raw', 'str'],
    default_virt_file_size: [5, 'int'],
    default_virt_ram: [512, 'int'],
    default_virt_type: ['auto', 'str'],
    enable_gpxe: [0, 'bool'],
    enable_menu: [1, 'bool'],
    http_port: [80, 'int'],
    include: [['/etc/cobbler/settings.d/*.settings'], 'list'],
    iso_template_dir: ['/etc/cobbler/iso', 'str'],
    kernel_options: [{}, 'dict'],
    ldap_anonymous_bind: [1, 'bool'],
    ldap_base_dn: ['DC=devel,DC=redhat,DC=com', 'str'],
    ldap_port: [389, 'int'],
    ldap_search_bind_dn: ['', 'str'],
    ldap_search_passwd: ['', 'str'],
    ldap_search_prefix: ['uid=', 'str'],
    ldap_server: ['grimlock.devel.redhat.com', 'str'],
    ldap_tls: ['on', 'str'],
    ldap_tls_cacertfile: ['', 'str'],
    ldap_tls_certfile: ['', 'str'],
    ldap_tls_keyfile: ['', 'str'],
    bind_manage_ipmi: [0, 'bool'],
    manage_dhcp: [0, 'bool'],
    manage_dns: [0, 'bool'],
    manage_forward_zones: [[], 'list'],
    manage_reverse_zones: [[], 'list'],
    manage_genders: [0, 'bool'],
    manage_rsync: [0, 'bool'],
    manage_tftp: [1, 'bool'],
    manage_tftpd: [1, 'bool'],
    mgmt_classes: [[], 'list'],
    mgmt_parameters: [{}, 'dict'],
    next_server: ['127.0.0.1', 'str'],
    nsupdate_enabled: [0, 'bool'],
    power_management_default_type: ['ipmitool', 'str'],
    proxy_url_ext: ['', 'str'],
    proxy_url_int: ['', 'str'],
    puppet_auto_setup: [0, 'bool'],
    puppet_parameterized_classes: [1, 'bool'],
    puppet_server: ['puppet', 'str'],
    puppet_version: [2, 'int'],
    puppetca_path: ['/usr/bin/puppet', 'str'],
    pxe_just_once: [1, 'bool'],
    nopxe_with_triggers: [1, 'bool'],
    redhat_management_permissive: [0, 'bool'],
    redhat_management_server: ['xmlrpc.rhn.redhat.com', 'str'],
    redhat_management_key: ['', 'str'],
    register_new_installs: [0, 'bool'],
    remove_old_puppet_certs_automatically: [0, 'bool'],
    replicate_repo_rsync_options: ['-avzH', 'str'],
    replicate_rsync_options: ['-avzH', 'str'],
    reposync_flags: ['-l -m -d', 'str'],
    restart_dhcp: [1, 'bool'],
    restart_dns: [1, 'bool'],
    run_install_triggers: [1, 'bool'],
    scm_track_enabled: [0, 'bool'],
    scm_track_mode: ['git', 'str'],
    scm_track_author: ['cobbler <cobbler@localhost>', 'str'],
    scm_push_script: ['/bin/true', 'str'],
    serializer_pretty_json: [0, 'bool'],
    server: ['127.0.0.1', 'str'],
    sign_puppet_certs_automatically: [0, 'bool'],
    signature_path: ['/var/lib/cobbler/distro_signatures.json', 'str'],
    signature_url: ['https://cobbler.github.io/signatures/3.0.x/latest.json', 'str'],
    tftpboot_location: ['/var/lib/tftpboot', 'str'],
    virt_auto_boot: [0, 'bool'],
    webdir: ['/var/www/cobbler', 'str'],
    webdir_whitelist: ['.link_cache', 'misc', 'distro_mirror', 'images', 'links', 'localmirror', 'pub', 'rendered', 'repo_mirror', 'repo_profile', 'repo_system', 'svc', 'web', 'webui'],
    xmlrpc_port: [25151, 'int'],
    yum_distro_priority: [1, 'int'],
    yum_post_install_mirror: [1, 'bool'],
    yumdownloader_flags: ['--resolve', 'str'],
  };

  constructor() {
  }

  getAll(): object {
    return this.mockdata;
  }

  getitem(name: string): any {
    const data = this.mockdata[name];
    const faildata = ['data not found', 'data not found'];
    if (data !== null) {
      return data;
    }
  }
}
