name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - name: Install Dependencies
        run: npm ci
      - name: Build doc
        run: npm run doc
      - name: Archive www Artifact
        uses: actions/upload-artifact@master
        with:
          name: documentation
          path: documentation
  deploy:
    name: Deploy 🚀
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: documentation
          path: documentation
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: documentation
          CLEAN: true
