name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-typescript-xmlrpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "lts/*"
      - name: NPM CI
        run: npm ci
      - name: Build project typescript-xmlrpc
        run: npm run build typescript-xmlrpc
      - name: Test Project
        run: npm run test:ci typescript-xmlrpc
      - name: Upload coverage report to GH artifacts
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report-typescript-xmlrpc
          path: coverage/typescript-xmlrpc/lcov.info
          if-no-files-found: error
  unit-cobbler-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "lts/*"
      - name: NPM CI
        run: npm ci
      - name: Build sibling project typescript-xmlrpc
        run: npm run build typescript-xmlrpc
      - name: Build project cobbler-api
        run: npm run build cobbler-api
      - name: Test Project
        run: npm run test:ci cobbler-api
      - name: Upload coverage report to GH artifacts
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report-cobbler-api
          path: coverage/cobbler-api/lcov.info
          if-no-files-found: error
  unit-cobbler-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "lts/*"
      - name: NPM CI
        run: npm ci
      - name: Build sibling project typescript-xmlrpc
        run: npm run build typescript-xmlrpc
      - name: Build sibling project cobbler-api
        run: npm run build cobbler-api
      - name: Build project
        run: npm run build cobbler-frontend
      - name: Test Project
        run: npm run test:ci cobbler-frontend
      - name: Upload coverage report to GH artifacts
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report-cobbler-frontend
          path: coverage/cobbler-frontend/lcov.info
          if-no-files-found: error
  e2e-cobbler-frontend:
    if: ${{ false }} # disable for now; we don't have e2e tests currently
    runs-on: ubuntu-latest
    container:
      image: timbru31/node-chrome:22
      env:
        CHROME_BIN: /usr/bin/google-chrome
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: NPM CI
        run: npm ci
      - name: Build sibling project typscript-xmlrpc
        run: npm run build typescript-xmlrpc
      - name: Build sibling project cobbler-api
        run: npm run build cobbler-api
      - name: Build project
        run: npm run build cobbler-frontend
      - name: E2E Tests
        run: npm run e2e -- --configuration=ci
